"use client";

import { useState } from "react";
import { Download, Check, X, FileText } from "lucide-react";
import { SURVEYS_BY_DATE_DESC, getFacility, getFtag } from "@/lib/mock-data";
import { SeverityBadge } from "@/components/dashboard/severity-badge";
import { formatDate, daysUntil, cn } from "@/lib/utils";
import { downloadPoc } from "@/lib/word-export";
import type { Survey } from "@/lib/types";

const PENDING = SURVEYS_BY_DATE_DESC.filter((s) => s.pocStatus !== "POC submitted");

type Decision = "pending" | "accepted" | "rejected";

export default function PocReviewPage() {
  const [selectedId, setSelectedId] = useState<string>(PENDING[0]?.id ?? "");
  // Decisions persist across survey switches in the same session.
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const selected = PENDING.find((s) => s.id === selectedId);

  function setDecision(surveyId: string, d: Decision) {
    setDecisions((prev) => ({ ...prev, [surveyId]: d }));
  }

  const decidedCount = Object.values(decisions).filter((d) => d !== "pending").length;

  return (
    <div className="px-10 pt-6 pb-16 max-w-[1500px]">
      <div className="mb-8 ph-reveal">
        <p className="text-base text-ph-gray-500 max-w-2xl leading-relaxed">
          Compliance review queue. Each draft was generated by the Foundry POC drafting agent
          with citations to historical accepted POCs. Edit, accept, or send to Word for
          finalization.
        </p>
      </div>

      <div className="grid grid-cols-12 gap-6">
        <aside className="col-span-12 md:col-span-4 ph-card overflow-hidden">
          <header className="px-5 py-4 border-b border-ph-gray-200 flex items-baseline justify-between">
            <div>
              <h3 className="text-base tracking-tight">Pending review</h3>
              <p className="text-[11px] text-ph-gray-500 mt-0.5">
                {PENDING.length} drafts
                {decidedCount > 0 && (
                  <span className="text-ph-primary"> · {decidedCount} decided this session</span>
                )}
              </p>
            </div>
          </header>
          <ul className="divide-y divide-ph-gray-200 max-h-[700px] overflow-y-auto">
            {PENDING.map((s) => (
              <PocListItem
                key={s.id}
                survey={s}
                selected={s.id === selectedId}
                decision={decisions[s.id] ?? "pending"}
                onSelect={() => setSelectedId(s.id)}
              />
            ))}
          </ul>
        </aside>

        <section className="col-span-12 md:col-span-8">
          {selected ? (
            <PocDetail
              survey={selected}
              decision={decisions[selected.id] ?? "pending"}
              setDecision={(d) => setDecision(selected.id, d)}
            />
          ) : (
            <EmptyState />
          )}
        </section>
      </div>
    </div>
  );
}

function PocListItem({
  survey,
  selected,
  decision,
  onSelect,
}: {
  survey: Survey;
  selected: boolean;
  decision: Decision;
  onSelect: () => void;
}) {
  const facility = getFacility(survey.facilityId)!;
  const dueIn = daysUntil(survey.pocDueDate);
  return (
    <li>
      <button
        type="button"
        onClick={onSelect}
        className={cn(
          "w-full text-left px-5 py-3 hover:bg-ph-gray-50 transition-colors",
          selected && "bg-ph-primary-soft border-l-2 border-ph-burgundy",
        )}
      >
        <div className="flex items-baseline justify-between mb-1">
          <span className="font-display text-sm tracking-tight inline-flex items-center gap-1.5">
            {decision === "accepted" && (
              <Check className="h-3 w-3 text-ph-primary" strokeWidth={2.5} aria-label="Accepted" />
            )}
            {decision === "rejected" && (
              <X className="h-3 w-3 text-ph-burgundy" strokeWidth={2.5} aria-label="Rejected" />
            )}
            {facility.name.replace("Pruitthealth ", "")}
          </span>
          <span
            className={cn(
              "text-[10px] font-mono",
              dueIn < 0 && "text-ph-burgundy",
              dueIn >= 0 && dueIn <= 3 && "text-ph-amber",
              dueIn > 3 && "text-ph-gray-400",
            )}
          >
            {dueIn < 0 ? `${Math.abs(dueIn)}d overdue` : `${dueIn}d`}
          </span>
        </div>
        <div className="flex flex-wrap gap-1 mb-1">
          {survey.deficiencies.slice(0, 3).map((d) => (
            <span key={d.ftag} className="inline-flex items-center rounded bg-ph-gray-100 px-1.5 py-0.5 text-[9px] font-mono text-ph-gray-700">
              {d.ftag}
            </span>
          ))}
        </div>
        <div className="text-[10px] text-ph-gray-500">{formatDate(survey.surveyDate)}</div>
      </button>
    </li>
  );
}

function PocDetail({
  survey,
  decision,
  setDecision,
}: {
  survey: Survey;
  decision: Decision;
  setDecision: (d: Decision) => void;
}) {
  const facility = getFacility(survey.facilityId)!;
  return (
    <div className="space-y-6">
      {/* Header card */}
      <div className="ph-card p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="ph-eyebrow text-ph-gray-400 mb-1">{formatDate(survey.surveyDate)}</div>
            <h2 className="text-2xl tracking-tight font-display">{facility.name}</h2>
            <p className="text-xs text-ph-gray-500 mt-1">{survey.surveyorOrg}</p>
            {decision !== "pending" && (
              <div className={cn(
                "mt-2 inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[11px] font-medium",
                decision === "accepted" && "bg-ph-primary-soft text-ph-primary",
                decision === "rejected" && "bg-ph-burgundy-soft text-ph-burgundy",
              )}>
                {decision === "accepted" ? "Accepted — ready to submit" : "Rejected — will be re-drafted"}
              </div>
            )}
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => setDecision("rejected")}
              disabled={decision === "rejected"}
              className="inline-flex items-center gap-1.5 rounded-lg border border-ph-gray-200 px-3 py-1.5 text-xs hover:bg-ph-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <X className="h-3 w-3" /> Reject
            </button>
            <button
              type="button"
              onClick={() => setDecision("accepted")}
              disabled={decision === "accepted"}
              className="inline-flex items-center gap-1.5 rounded-lg bg-ph-primary text-white px-3 py-1.5 text-xs hover:bg-ph-primary-dark disabled:opacity-70 disabled:cursor-not-allowed"
            >
              <Check className="h-3 w-3" /> Accept
            </button>
            <button
              type="button"
              onClick={() => downloadPoc(survey, facility)}
              className="inline-flex items-center gap-1.5 rounded-lg border border-ph-burgundy text-ph-burgundy px-3 py-1.5 text-xs hover:bg-ph-burgundy-soft"
            >
              <Download className="h-3 w-3" /> Send to Word
            </button>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          {survey.deficiencies.map((d) => (
            <span key={d.ftag} className="inline-flex items-center gap-1.5 rounded bg-ph-gray-100 px-2 py-1 text-[11px]">
              <span className="font-mono text-ph-burgundy">{d.ftag}</span>
              <span className="text-ph-gray-700">— {getFtag(d.ftag)?.shortTitle}</span>
              <SeverityBadge severity={d.severity} compact />
            </span>
          ))}
        </div>
      </div>

      {/* Activities */}
      <div className="ph-card overflow-hidden">
        <header className="px-6 py-4 border-b border-ph-gray-200">
          <h3 className="text-lg tracking-tight">Drafted activities</h3>
          <p className="text-[11px] text-ph-gray-500 mt-0.5">
            {survey.pocActivities.length} corrective steps · each cites a historical accepted POC
          </p>
        </header>
        <ol className="divide-y divide-ph-gray-200">
          {survey.pocActivities.map((a, i) => (
            <li key={a.id} className="px-6 py-5">
              <div className="flex items-start gap-4">
                <span className="flex h-6 w-6 items-center justify-center rounded-full bg-ph-primary-soft text-ph-primary text-[11px] font-display font-medium shrink-0">
                  {i + 1}
                </span>
                <div className="flex-1">
                  <p className="text-sm text-ph-ink leading-relaxed">{a.text}</p>
                  <div className="mt-2 flex items-center gap-3 text-[11px] text-ph-gray-500">
                    <span>Target: {a.targetCompletionDate}</span>
                    <span className="text-ph-gray-300">·</span>
                    <span className="font-mono text-ph-burgundy">{a.citation.exemplarFtag}</span>
                  </div>
                  <blockquote className="mt-2 border-l-2 border-ph-sage/50 pl-3 text-[11px] italic text-ph-gray-500 leading-relaxed">
                    "{a.citation.quote}"
                    <span className="block not-italic font-mono text-[10px] text-ph-gray-400 mt-1">
                      — {a.citation.exemplarId}
                    </span>
                  </blockquote>
                </div>
              </div>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="ph-card p-12 text-center">
      <FileText className="h-10 w-10 text-ph-gray-400 mx-auto mb-4" strokeWidth={1.4} />
      <h3 className="text-lg mb-2 tracking-tight">No drafts pending review</h3>
      <p className="text-sm text-ph-gray-500">All POCs are submitted.</p>
    </div>
  );
}
