/*
 * KPI glossary — plain-English definitions surfaced as tooltips on every KPI
 * tile (the vendor demo's strongest "audience-aware" concept, ported verbatim).
 */
export const KPI_DEFS: Record<string, string> = {
  "TTM Revenue": "Total revenue over the trailing twelve months, across all locations.",
  "Region Revenue": "Trailing-twelve-month revenue for the locations in this region.",
  "Facility Revenue": "Trailing-twelve-month revenue for this single location.",
  "Revenue (month)": "Total revenue billed in the month.",
  "Region Revenue (month)": "Total revenue billed in the month for this region.",
  "Facility Revenue (month)": "Total revenue billed in the month for this location.",
  "Operating Margin": "Profit left after running costs, as a % of revenue. Higher is better — target ~9%.",
  "Avg Occupancy": "Share of available beds that are filled. Higher = more residents served.",
  Occupancy: "Share of available beds that are filled. Higher = more residents served.",
  "Occupancy / Census": "Share of beds filled (census = number of residents living there).",
  "Agency Hours": "Share of nursing hours filled by costly temporary agency staff. Lower is better.",
  "Agency Cost": "Temporary-staffing as a share of nursing hours — a key cost pressure. Lower is better.",
  "Open Survey Citations": "State-inspection deficiencies cited in the last 90 days. Lower is better.",
  "POC On-Time Rate": "Share of Plans of Correction filed inside the 10-day regulatory deadline.",
  "POC In Queue": "Plans of Correction assigned to you awaiting drafting or review.",
  "POC Due": "Days remaining to file the Plan of Correction inside the 10-day window.",
  "Labor % of Revenue": "Staff cost as a share of revenue — the single biggest cost lever in post-acute care.",
  "PDPM Case-Mix Index": "How clinically complex residents are; drives Medicare payment per day. Higher = sicker, higher-paying mix.",
  "Immediate Jeopardy": "Most severe citation level — actual or likely serious harm. Requires immediate correction.",
  "Clinical / QoC (12m)": "Clinical / Quality-of-Care citations over the trailing twelve months.",
  "Infection Control": "Infection-prevention citations (e.g. F880) over the trailing twelve months.",
  "Needs Validation": "AI extractions below confidence threshold, held for a human to check.",
  "Max Model Drift": "Largest drift across production models vs the alert threshold; high drift triggers retraining.",
  "Assigned Facilities": "Facilities in your review scope with open surveys.",
  "Avg Extraction Conf.": "Average confidence of the AI document extraction across your queue.",
  "Pipelines Healthy": "Healthy data pipeline stages out of total (source → index).",
  "Stale Sources": "Source systems whose last refresh is behind schedule.",
  "Extraction Conf.": "Average confidence of CMS-2567 document extraction.",
  "Docs Indexed": "Survey documents indexed for source-grounded retrieval.",
  "Uptime (30d)": "Platform availability over the trailing 30 days.",
  "Critical (open)": "Open alerts at critical severity.",
  "Warning (open)": "Open alerts at warning severity.",
  "SLA on-time": "Share of alerts delivered within the routing SLA, generation to delivery.",
  Channels: "Delivery channels alerts are routed to, per rule.",
};
